import React, { useState, useEffect, useRef } from 'react';
import { X, Plus, Trash2, RefreshCw, Image as ImageIcon, Video, Wand2, ChevronLeft, ChevronRight, Check, AlertCircle, Download } from 'lucide-react';
import videoStoryboardService from '../services/videoStoryboardService';
import { uploadService } from '../services/uploadService';
import poppyImg from '../assets/ip/poppy.png';
import ediImg from '../assets/ip/edi.png';
import rollyImg from '../assets/ip/rolly.png';
import miloImg from '../assets/ip/milo.png';
import aceImg from '../assets/ip/ace.png';

// 步骤定义
const STEPS = [
  { id: 1, title: '基本信息', description: '输入视频描述' },
  { id: 2, title: '分镜详情', description: '查看分镜信息' },
  { id: 3, title: '生成视频', description: '合成最终视频' }
];

// 图片比例选项
const ASPECT_RATIOS = [
  { id: '16:9', label: '16:9', width: 1280, height: 720, description: '横屏宽屏' },
  { id: '4:3', label: '4:3', width: 1280, height: 960, description: '标准横屏' },
  { id: '1:1', label: '1:1', width: 1280, height: 1280, description: '正方形' },
  { id: '3:4', label: '3:4', width: 960, height: 1280, description: '标准竖屏' },
  { id: '9:16', label: '9:16', width: 720, height: 1280, description: '竖屏长图' },
];

// IP角色数据（与RoleSelection.jsx保持一致）
const IP_CHARACTERS = [
  { id: 'poppy', name: 'Poppy', color: '粉色', colorHex: '#FFB6C1', description: '粉色角色', thumbnail: poppyImg, available: true },
  { id: 'edi', name: 'Edi', color: '蓝色', colorHex: '#87CEEB', description: '蓝色角色', thumbnail: ediImg, available: true },
  { id: 'rolly', name: 'Rolly', color: '橘色', colorHex: '#FFA500', description: '橘色角色', thumbnail: rollyImg, available: true },
  { id: 'milo', name: 'Milo', color: '黄色', colorHex: '#FFD700', description: '黄色角色', thumbnail: miloImg, available: true },
  { id: 'ace', name: 'Ace', color: '紫色', colorHex: '#9370DB', description: '紫色角色', thumbnail: aceImg, available: true },
];

/**
 * VideoStoryboardModal - 视频分镜向导式编辑模态框
 * 分步骤完成视频生成：基本信息 → 人物参考 → 分镜脚本 → 分镜图片 → 生成视频
 */
export const VideoStoryboardModal = ({
  isOpen,
  onClose,
  initialDescription = '',
  onConfirm,
  userId = null,
  organizationId = null
}) => {
  // 当前步骤
  const [currentStep, setCurrentStep] = useState(1);
  
  // 步骤1：基本信息
  const [storyCore, setStoryCore] = useState('');
  const [selectedAspectRatio, setSelectedAspectRatio] = useState(ASPECT_RATIOS[0]); // 默认16:9
  const [selectedIPs, setSelectedIPs] = useState([]); // 选中的IP列表
  
  // 步骤2：分镜生成
  const [storyboardTitle, setStoryboardTitle] = useState('');
  const [scenes, setScenes] = useState([]);
  const [isGeneratingScript, setIsGeneratingScript] = useState(false);
  const [editingScene, setEditingScene] = useState(null); // { sceneId, field } 或 null
  const [isGeneratingSceneImage, setIsGeneratingSceneImage] = useState({}); // sceneId -> boolean
  const [uploadingSceneImage, setUploadingSceneImage] = useState({}); // sceneId -> boolean
  
  // 分镜详细信息
  const [storyboardData, setStoryboardData] = useState(null); // 存储完整的storyboardData
  const [voiceInfo, setVoiceInfo] = useState(null); // 配音信息
  const [characterPrompt, setCharacterPrompt] = useState(''); // 角色提示词
  const [videoSize, setVideoSize] = useState({ width: 1920, height: 1080 }); // 视频尺寸，默认16:9
  
  // 步骤3：视频生成
  const [isComposingVideo, setIsComposingVideo] = useState(false);
  const [generatedVideoUrl, setGeneratedVideoUrl] = useState(null);
  
  // 全局状态
  const [error, setError] = useState(null);
  
  // 分镜图片预览（放大查看）
  const [previewImage, setPreviewImage] = useState(null); // { url: string, alt: string } | null

  const closePreviewImage = () => setPreviewImage(null);

  useEffect(() => {
    if (!previewImage) return;
    const onKeyDown = (e) => {
      if (e.key === 'Escape') closePreviewImage();
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [previewImage]);

  const hasAutoGenerated = useRef(false);

  // 同步 videoSize 和 selectedAspectRatio
  useEffect(() => {
    if (!storyboardData) {
      setVideoSize({ width: selectedAspectRatio.width, height: selectedAspectRatio.height });
    }
  }, [selectedAspectRatio, storyboardData]);

  // 初始化（仅在 isOpen 从 false→true 时执行一次）
  useEffect(() => {
    if (!isOpen) return;

    setCurrentStep(1);
    setStoryCore('');
    setSelectedAspectRatio(ASPECT_RATIOS[0]);
    setSelectedIPs([]);
    setStoryboardTitle('');
    setScenes([]);
    setIsGeneratingSceneImage({});
    setIsComposingVideo(false);
    setGeneratedVideoUrl(null);
    setError(null);
    setPreviewImage(null);
    setStoryboardData(null);
    setVideoSize({ width: ASPECT_RATIOS[0].width, height: ASPECT_RATIOS[0].height });
    hasAutoGenerated.current = false;
  }, [isOpen]);

  // 自动生成分镜脚本和图片（已禁用，现在在handleStep1Next中调用webhook）
  // useEffect(() => {
  //   if (currentStep === 2 && scenes.length === 0 && !isGeneratingScript && !hasAutoGenerated.current) {
  //     hasAutoGenerated.current = true;
  //     generateStoryboardScript();
  //   }
  //   if (currentStep !== 2) {
  //     hasAutoGenerated.current = false;
  //   }
  // }, [currentStep, scenes.length]);

  // 获取最终参考图片（不再使用，返回空数组）
  const getFinalReferenceImages = () => {
    return [];
  };

  // 获取组合的视频描述（三个维度）
  const getCombinedDescription = () => {
    const selectedIPNames = selectedIPs.map(id => {
      const ip = IP_CHARACTERS.find(p => p.id === id);
      return ip ? ip.name : '';
    }).filter(name => name).join('、');
    
    let description = `故事核心要素：${storyCore}`;
    if (selectedIPNames) {
      description += `\nIP选择：${selectedIPNames}`;
    }
    return description;
  };

  // ========== 步骤1：基本信息 ==========
  
  // 步骤1下一步
  const handleStep1Next = async () => {
    if (!storyCore.trim()) {
      setError('请填写故事核心要素');
      return;
    }

    if (selectedIPs.length === 0) {
      setError('请选择一个IP角色');
      return;
    }

    setIsGeneratingScript(true);
    setError(null);

    try {
      console.log('开始调用webhook生成图片...');
      console.log('选择的视频比例:', selectedAspectRatio);
      console.log('selectedAspectRatio.width:', selectedAspectRatio.width);
      console.log('selectedAspectRatio.height:', selectedAspectRatio.height);
      
      const result = await videoStoryboardService.callWebhookGenerateImages(
        selectedIPs[0],
        selectedAspectRatio.id,
        storyCore,
        selectedAspectRatio.width,
        selectedAspectRatio.height
      );

      console.log('生成分镜结果:', result);

      if (result && result.storyboardData) {
        console.log('storyboardData:', result.storyboardData);
        
        const { 
          storyboard_images_filepath, 
          storyboard_prompts, 
          voice, 
          character_prompt,
          video_width,
          video_height,
          storyboard_image_prompts
        } = result.storyboardData;
        
        console.log('N8N返回的视频尺寸:', video_width, 'x', video_height);
        console.log('第一步选择的视频尺寸:', selectedAspectRatio.width, 'x', selectedAspectRatio.height);
        
        // 强制使用第一步选择的尺寸
        const finalVideoWidth = selectedAspectRatio.width;
        const finalVideoHeight = selectedAspectRatio.height;
        
        // 存储完整的storyboardData，确保包含视频尺寸
        const completeStoryboardData = {
          ...result.storyboardData,
          video_width: finalVideoWidth,
          video_height: finalVideoHeight
        };
        
        setStoryboardData(completeStoryboardData);
        setVoiceInfo(voice);
        setCharacterPrompt(character_prompt);
        setVideoSize({ width: finalVideoWidth, height: finalVideoHeight });
        
        console.log('最终使用的视频尺寸:', finalVideoWidth, 'x', finalVideoHeight);
        
        if (storyboard_images_filepath && Array.isArray(storyboard_images_filepath) && storyboard_images_filepath.length > 0) {
          console.log('找到图片路径:', storyboard_images_filepath);
          console.log('找到分镜提示词:', storyboard_prompts);
          console.log('找到配音信息:', voice);
          console.log('找到角色提示词:', character_prompt);
          console.log('找到分镜图片提示词:', storyboard_image_prompts);
          
          const newScenes = storyboard_images_filepath.map((imagePath, index) => {
            const imageUrl = imagePath.startsWith('/home/node/files/') 
              ? `/api/ai/serve-image?path=${encodeURIComponent(imagePath)}`
              : imagePath;
            
            return {
              id: `scene-${index + 1}`,
              sequence: index + 1,
              description: storyboard_prompts && storyboard_prompts[index] ? storyboard_prompts[index].description : `分镜${index + 1}`,
              prompt: storyboard_prompts && storyboard_prompts[index] ? storyboard_prompts[index].prompt : '',
              duration: storyboard_prompts && storyboard_prompts[index] ? storyboard_prompts[index].duration : 3,
              generatedImage: imageUrl,
              imagePrompt: storyboard_image_prompts && storyboard_image_prompts[index] ? storyboard_image_prompts[index].prompt : '',
              thoughtProcess: storyboard_image_prompts && storyboard_image_prompts[index] ? storyboard_image_prompts[index].thought_process : '',
              status: 'completed'
            };
          });
          
          setScenes(newScenes);
          setStoryboardTitle(storyCore);
          setCurrentStep(2);
          console.log('成功生成分镜，跳转到步骤2');
        } else {
          console.error('未找到图片数据');
          throw new Error('未找到图片数据');
        }
      } else {
        console.error('返回数据格式错误:', result);
        throw new Error('未返回有效数据');
      }
    } catch (err) {
      console.error('生成分镜失败:', err);
      setError('生成分镜失败: ' + err.message);
    } finally {
      setIsGeneratingScript(false);
    }
  };

  // 生成分镜图片
  const handleGenerateSceneImage = async (sceneId, sceneOverride = null) => {
    const scene = sceneOverride || scenes.find(s => s.id === sceneId);
    if (!scene) return;

    setIsGeneratingSceneImage(prev => ({ ...prev, [sceneId]: true }));
    setError(null);

    try {
      console.log('重新生成图片，场景:', scene);
      
      // 使用 imagePrompt（图片提示词）而不是 prompt（视频提示词）
      const prompt = scene.imagePrompt || scene.prompt;
      
      // 获取视频尺寸
      const width = videoSize.width;
      const height = videoSize.height;
      
      // 获取角色名称
      const role = selectedIPs[0] || 'poppy'; // 默认使用 poppy
      
      console.log('调用重新生成图片API，参数:', { width, height, role, prompt });
      
      // 调用重新生成图片API并轮询
      const result = await videoStoryboardService.regeneImageWithPolling(
        width,
        height,
        role,
        prompt
      );
      
      console.log('重新生成图片结果:', result);
      
      // 更新场景的图片URL
      let newImageUrl;
      if (typeof result === 'string') {
        newImageUrl = result;
      } else if (result.storyboardData) {
        // 后端返回格式：{ status: 'completed', storyboardData: { data: 'http://...' } }
        if (typeof result.storyboardData === 'string') {
          newImageUrl = result.storyboardData;
        } else if (result.storyboardData.data) {
          newImageUrl = result.storyboardData.data;
        } else {
          console.error('storyboardData格式未知:', result.storyboardData);
          throw new Error('未找到图片URL');
        }
      } else if (result.image_url) {
        newImageUrl = result.image_url;
      } else if (result.url) {
        newImageUrl = result.url;
      } else if (result.data) {
        // 可能直接是 { data: 'http://...' }
        if (typeof result.data === 'string') {
          newImageUrl = result.data;
        } else {
          console.error('data格式未知:', result.data);
          throw new Error('未找到图片URL');
        }
      } else {
        console.error('未知的返回格式:', result);
        throw new Error('未找到图片URL');
      }
      
      console.log('新图片URL:', newImageUrl);
      
      setScenes(prev => prev.map(s => 
        s.id === sceneId 
          ? { ...s, generatedImage: newImageUrl, status: 'completed' }
          : s
      ));
      
      return newImageUrl;
    } catch (err) {
      console.error('重新生成图片失败:', err);
      setError('重新生成图片失败: ' + err.message);
      return null;
    } finally {
      setIsGeneratingSceneImage(prev => ({ ...prev, [sceneId]: false }));
    }
  };

  // 生成所有分镜图片
  const handleGenerateAllSceneImages = async () => {
    for (const scene of scenes) {
      if (!scene.generatedImage) {
        await handleGenerateSceneImage(scene.id);
      }
    }
  };

  // 添加新分镜
  const handleAddScene = () => {
    const newSceneId = `scene-${Date.now()}`;
    const newScene = {
      id: newSceneId,
      sequence: scenes.length + 1,
      description: '',
      prompt: '',
      duration: 3,
      generatedImage: null,
      imagePrompt: '',
      thoughtProcess: '',
      status: 'pending'
    };
    setScenes([...scenes, newScene]);
  };

  // 删除分镜
  const handleDeleteScene = (sceneId) => {
    const updatedScenes = scenes
      .filter(scene => scene.id !== sceneId)
      .map((scene, index) => ({
        ...scene,
        sequence: index + 1
      }));
    setScenes(updatedScenes);
  };

  // 上移分镜
  const handleMoveSceneUp = (sceneId) => {
    const index = scenes.findIndex(s => s.id === sceneId);
    if (index <= 0) return; // 已经是第一个
    
    const newScenes = [...scenes];
    [newScenes[index - 1], newScenes[index]] = [newScenes[index], newScenes[index - 1]];
    
    // 更新序号
    const updatedScenes = newScenes.map((scene, idx) => ({
      ...scene,
      sequence: idx + 1
    }));
    
    setScenes(updatedScenes);
  };

  // 下移分镜
  const handleMoveSceneDown = (sceneId) => {
    const index = scenes.findIndex(s => s.id === sceneId);
    if (index >= scenes.length - 1) return; // 已经是最后一个
    
    const newScenes = [...scenes];
    [newScenes[index], newScenes[index + 1]] = [newScenes[index + 1], newScenes[index]];
    
    // 更新序号
    const updatedScenes = newScenes.map((scene, idx) => ({
      ...scene,
      sequence: idx + 1
    }));
    
    setScenes(updatedScenes);
  };

  // 上传分镜图片
  const handleUploadSceneImage = async (sceneId, e) => {
    const file = e.target.files[0];
    if (!file) return;

    setError(null);
    setUploadingSceneImage(prev => ({ ...prev, [sceneId]: true }));

    try {
      const validation = uploadService.validateFile(file, ['image/jpeg', 'image/png', 'image/gif', 'image/webp'], 10);
      if (!validation.valid) {
        setError(validation.error || '文件验证失败');
        return;
      }

      const uploadResult = await uploadService.uploadFile(file, 'scene-images');

      if (uploadResult.success && uploadResult.url) {
        setScenes(prev => prev.map(scene => 
          scene.id === sceneId 
            ? { ...scene, generatedImage: uploadResult.url, status: 'completed' }
            : scene
        ));
      } else {
        setError(uploadResult.error || '上传失败');
      }
    } catch (err) {
      console.error('上传分镜图片失败:', err);
      setError('上传失败: ' + err.message);
    } finally {
      setUploadingSceneImage(prev => {
        const newState = { ...prev };
        delete newState[sceneId];
        return newState;
      });
      e.target.value = '';
    }
  };

  // 更新分镜信息
  const handleUpdateScene = (sceneId, field, value) => {
    setScenes(prev => prev.map(scene => 
      scene.id === sceneId 
        ? { ...scene, [field]: value }
        : scene
    ));
  };

  // 步骤2下一步 → 跳到步骤3（生成视频）
  const handleStep2Next = () => {
    const completedScenes = scenes.filter(s => s.generatedImage);
    if (completedScenes.length === 0) {
      setError('请先生成至少一张分镜图片');
      return;
    }
    setCurrentStep(3);
  };

  // ========== 步骤3：生成视频 ==========
  
  // 合成视频
  const handleComposeVideo = async () => {
    setIsComposingVideo(true);
    setError(null);

    try {
      console.log('开始生成视频...');
      console.log('当前分镜数据:', scenes);
      
      // 从当前的 scenes 数据构建请求数据
      const storyboard_images_filepath = scenes.map(scene => {
        // 如果图片URL是本地代理路径，转换回原始路径
        if (scene.generatedImage && scene.generatedImage.includes('/api/ai/serve-image')) {
          const urlParams = new URLSearchParams(scene.generatedImage.split('?')[1]);
          return urlParams.get('path') || scene.generatedImage;
        }
        return scene.generatedImage || '';
      });
      
      const storyboard_prompts = scenes.map(scene => ({
        prompt: scene.prompt || '',
        duration: scene.duration || 3,
        description: scene.description || ''
      }));
      
      const storyboard_image_prompts = scenes.map(scene => ({
        prompt: scene.imagePrompt || scene.prompt || '',
        thought_process: scene.thoughtProcess || ''
      }));
      
      // 构建完整的请求数据
      const requestData = {
        storyboard_images_filepath,
        storyboard_prompts,
        video_width: videoSize.width,
        video_height: videoSize.height,
        voice: voiceInfo || storyboardData?.voice || {},
        storyboard_image_prompts
      };
      
      console.log('构建的请求数据:', JSON.stringify(requestData, null, 2));
      
      // 验证必要字段
      const requiredFields = [
        'storyboard_images_filepath',
        'storyboard_prompts',
        'video_width',
        'video_height',
        'voice',
        'storyboard_image_prompts'
      ];
      
      const missingFields = requiredFields.filter(field => !requestData[field]);
      if (missingFields.length > 0) {
        console.error('缺少必要字段:', missingFields);
        throw new Error(`缺少必要字段: ${missingFields.join(', ')}`);
      }
      
      console.log('数据验证通过，所有必要字段都存在');
      console.log('图片数量:', requestData.storyboard_images_filepath.length);
      console.log('提示词数量:', requestData.storyboard_prompts.length);
      console.log('视频尺寸:', requestData.video_width, 'x', requestData.video_height);
      console.log('配音角色数量:', requestData.voice.characters_timbre?.length);
      console.log('配音脚本数量:', requestData.voice.voice_scripts?.length);
      
      const result = await videoStoryboardService.generateVideoWithPolling(requestData);
      
      console.log('视频生成结果:', result);
      
      // 检查返回的视频数据
      if (result && result.videoData) {
        // videoData 可能是字符串（直接是URL）或对象
        let videoUrl;
        if (typeof result.videoData === 'string') {
          videoUrl = result.videoData;
        } else {
          videoUrl = result.videoData.video_url || result.videoData.url || result.videoData.videoUrl || result.videoData.data;
        }
        
        if (videoUrl) {
          console.log('视频URL:', videoUrl);
          setGeneratedVideoUrl(videoUrl);
        } else {
          console.error('视频数据结构:', result.videoData);
          throw new Error('未找到视频URL');
        }
      } else {
        throw new Error('未返回视频数据');
      }
    } catch (err) {
      console.error('合成视频失败:', err);
      setError('合成视频失败: ' + err.message);
    } finally {
      setIsComposingVideo(false);
    }
  };

  // 确认完成
  const handleConfirm = () => {
    onConfirm({
      title: storyboardTitle,
      description: getCombinedDescription(),
      referenceImages: getFinalReferenceImages(),
      scenes,
      videoUrl: generatedVideoUrl
    });
  };

  // 渲染步骤指示器
  const renderStepIndicator = () => (
    <div className="flex items-center justify-center mb-6">
      {STEPS.map((step, index) => (
        <React.Fragment key={step.id}>
          <div className={`flex flex-col items-center ${currentStep === step.id ? 'text-purple-600' : currentStep > step.id ? 'text-green-600' : 'text-slate-400'}`}>
            <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium ${
              currentStep === step.id ? 'bg-purple-100 border-2 border-purple-600' :
              currentStep > step.id ? 'bg-green-100 border-2 border-green-600' :
              'bg-[#fcfbf9] border-2 border-[#d1d5db]'
            }`}>
              {currentStep > step.id ? <Check className="w-4 h-4" /> : step.id}
            </div>
            <span className="text-xs mt-1 hidden sm:block">{step.title}</span>
          </div>
          {index < STEPS.length - 1 && (
            <div className={`w-12 h-0.5 mx-2 ${currentStep > step.id ? 'bg-green-500' : 'bg-slate-200'}`} />
          )}
        </React.Fragment>
      ))}
    </div>
  );

  // 渲染步骤1：基本信息
  const renderStep1 = () => (
    <div className="relative">
      {isGeneratingScript && (
        <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center rounded-xl">
          <RefreshCw className="w-10 h-10 text-purple-500 animate-spin mb-4" />
          <p className="text-slate-600 font-medium">正在生成分镜图片...</p>
          <p className="text-sm text-slate-400 mt-1">请稍候，这可能需要几分钟</p>
        </div>
      )}
      
      <div>
        <label className="text-sm font-medium text-slate-700 mb-2 block">
          故事核心要素 <span className="text-red-500">*</span>
        </label>
        <textarea
          value={storyCore}
          onChange={(e) => setStoryCore(e.target.value)}
          placeholder="例如：poppy在花园里玩耍"
          className="w-full border-2 border-[#e5e3db] rounded-xl p-3 text-sm focus:ring-2 focus:ring-[#2d2d2d] focus:border-[#2d2d2d] outline-none resize-none h-24 transition-all"
          disabled={isGeneratingScript}
        />
      </div>

      <div>
        <label className="text-sm font-medium text-slate-700 mb-2 block">
          图片比例
        </label>
        <div className="grid grid-cols-5 gap-2">
          {ASPECT_RATIOS.map((ratio) => (
            <button
              key={ratio.id}
              onClick={() => setSelectedAspectRatio(ratio)}
              disabled={isGeneratingScript}
              className={`flex flex-col items-center justify-center p-2 rounded-lg border-2 transition-all ${
                selectedAspectRatio.id === ratio.id
                  ? 'border-purple-500 bg-purple-50 text-purple-700'
                  : 'border-2 border-[#e5e3db] hover:border-[#2d2d2d] text-[#2d2d2d] hover:bg-[#fffbe6]'
              }`}
            >
              <div 
                className="bg-current rounded-sm mb-1"
                style={{
                  width: ratio.id === '16:9' ? '32px' :
                         ratio.id === '4:3' ? '24px' :
                         ratio.id === '1:1' ? '20px' :
                         ratio.id === '3:4' ? '15px' : '12px',
                  height: ratio.id === '16:9' ? '18px' :
                          ratio.id === '4:3' ? '18px' :
                          ratio.id === '1:1' ? '20px' :
                          ratio.id === '3:4' ? '20px' : '21px'
                }}
              />
              <span className="text-xs font-medium">{ratio.label}</span>
            </button>
          ))}
        </div>
        <p className="text-xs text-slate-400 mt-1">
          已选择：{selectedAspectRatio.label} ({selectedAspectRatio.width}×{selectedAspectRatio.height}) - {selectedAspectRatio.description}
        </p>
      </div>

      <div>
        <label className="text-sm font-medium text-slate-700 mb-2 block">
          IP选择（单选）
        </label>
        <p className="text-xs text-slate-400 mb-3">
          选择要出现在视频中的IP角色
        </p>
        <div className="flex gap-3 flex-wrap">
          {IP_CHARACTERS.map((ip) => {
            const isSelected = selectedIPs.includes(ip.id);
            const isAvailable = ip.available !== false;
            return (
              <button
                key={ip.id}
                onClick={() => {
                  if (!isAvailable) return;
                  if (isSelected) {
                    setSelectedIPs([]);
                  } else {
                    setSelectedIPs([ip.id]);
                  }
                }}
                disabled={!isAvailable || isGeneratingScript}
                className={`relative flex flex-col items-center justify-center p-2 rounded-xl border-2 transition-all w-24 shrink-0 ${
                  !isAvailable
                    ? 'border-gray-200 bg-gray-50 cursor-not-allowed opacity-60'
                    : isSelected
                    ? 'border-purple-500 bg-purple-50'
                    : 'border-[#e5e3db] hover:border-[#2d2d2d] hover:bg-[#fffbe6]'
                }`}
              >
                {isSelected && isAvailable && (
                  <div className="absolute -top-1 -right-1 w-5 h-5 bg-purple-600 rounded-full flex items-center justify-center z-10">
                    <Check className="w-3 h-3 text-white" />
                  </div>
                )}
                <img
                  src={ip.thumbnail}
                  alt={ip.name}
                  className="w-full h-30 object-cover rounded-lg"
                />
                <span className={`text-xs font-medium mt-1.5 ${!isAvailable ? 'text-gray-400' : 'text-slate-800'}`}>
                  {ip.name}
                </span>
                <span
                  className="text-xs px-2 py-0.5 rounded-full mt-1"
                  style={{
                    backgroundColor: ip.colorHex,
                    color: '#FFF'
                  }}
                >
                  {ip.color}
                </span>
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );

  // 渲染步骤2：分镜图片详情
  const renderStep2 = () => (
    <div className="space-y-6">
      {/* 分镜脚本部分 */}
      {scenes.length === 0 ? (
        <div className="text-center py-8">
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 mb-4">
            <p className="text-yellow-700">
              未找到分镜数据，请返回步骤1重新生成
            </p>
          </div>
        </div>
      ) : (
        <>
          {/* 视频信息概览 */}
          <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-lg p-4">
            <h4 className="font-medium text-purple-800 mb-3">视频信息</h4>
            <div className="grid grid-cols-3 gap-4 text-sm">
              <div>
                <span className="text-slate-500">标题：</span>
                <span className="font-medium text-slate-700">{storyboardTitle}</span>
              </div>
              <div>
                <span className="text-slate-500">分镜数量：</span>
                <span className="font-medium text-slate-700">{scenes.length} 个</span>
              </div>
              <div>
                <span className="text-slate-500">视频尺寸：</span>
                <span className="font-medium text-slate-700">{videoSize.width} × {videoSize.height}</span>
              </div>
            </div>
          </div>

          {/* 角色提示词 */}
          {characterPrompt && (
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h4 className="font-medium text-blue-800 mb-2">角色描述</h4>
              <p className="text-sm text-blue-700">{characterPrompt}</p>
            </div>
          )}

          {/* 配音信息 */}
          {voiceInfo && voiceInfo.voice_scripts && voiceInfo.voice_scripts.length > 0 && (
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <h4 className="font-medium text-green-800 mb-3">配音信息</h4>
              <div className="space-y-2">
                {voiceInfo.characters_timbre && voiceInfo.characters_timbre.length > 0 && (
                  <div className="text-sm text-green-700 mb-2">
                    <span className="font-medium">音色：</span>
                    {voiceInfo.characters_timbre.map((timbre, index) => (
                      <span key={index} className="ml-2 px-2 py-0.5 bg-green-100 rounded text-xs">
                        {timbre.timbre_name} - {timbre.timbre_des}
                      </span>
                    ))}
                  </div>
                )}
                <div className="grid grid-cols-1 gap-2">
                  {voiceInfo.voice_scripts.map((script, index) => (
                    <div key={index} className="flex items-center gap-2 text-sm bg-white p-2 rounded border border-green-100">
                      <span className="text-green-600 font-mono text-xs">
                        [{(script.start_time / 1000).toFixed(1)}s - {(script.end_time / 1000).toFixed(1)}s]
                      </span>
                      <span className="text-slate-700">{script.text}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* 分镜图片部分 */}
          <div className="flex items-center justify-between">
            <h4 className="font-medium text-slate-700">分镜详情</h4>
            <button
              onClick={handleAddScene}
              className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors flex items-center gap-2 text-sm"
            >
              <Plus className="w-4 h-4" />
              添加分镜
            </button>
          </div>

          <div className="grid grid-cols-1 gap-4 overflow-y-auto">
            {scenes.map((scene) => (
              <div key={scene.id} className="border-2 border-[#e5e3db] rounded-xl overflow-hidden transition-all hover:border-[#2d2d2d]">
                <div className="flex gap-4 p-4">
                  {/* 图片 */}
                  <div className="w-64 shrink-0 flex flex-col justify-center">
                    <div className="h-36 bg-slate-100 relative rounded-lg overflow-hidden flex items-center justify-center mb-2">
                      {/* Loading 覆盖层 */}
                      {isGeneratingSceneImage[scene.id] && (
                        <div className="absolute inset-0 bg-black bg-opacity-50 flex items-center justify-center z-10">
                          <div className="text-white text-center">
                            <RefreshCw className="w-8 h-8 animate-spin mx-auto mb-2" />
                            <span className="text-sm">重新生成中...</span>
                          </div>
                        </div>
                      )}
                      
                      {scene.generatedImage ? (
                        <button
                          type="button"
                          onClick={() => setPreviewImage({ url: scene.generatedImage, alt: `分镜${scene.sequence}` })}
                          className="w-full h-full cursor-zoom-in flex items-center justify-center"
                          title="点击放大查看"
                        >
                          <img
                            src={scene.generatedImage}
                            alt={`分镜${scene.sequence}`}
                            className="max-w-full max-h-full object-contain"
                          />
                        </button>
                      ) : (
                        <div className="w-full h-full flex items-center justify-center text-slate-400">
                          <ImageIcon className="w-8 h-8" />
                        </div>
                      )}
                    </div>
                    
                    {/* 图片操作按钮 */}
                    <div className="flex gap-1">
                      <input
                        type="file"
                        accept="image/jpeg,image/png,image/gif,image/webp"
                        onChange={(e) => handleUploadSceneImage(scene.id, e)}
                        className="hidden"
                        id={`upload-scene-${scene.id}`}
                      />
                      <label
                        htmlFor={`upload-scene-${scene.id}`}
                        className={`flex-1 px-2 py-1.5 text-xs bg-slate-100 hover:bg-slate-200 rounded text-center cursor-pointer transition-colors ${
                          uploadingSceneImage[scene.id] ? 'opacity-50 cursor-not-allowed' : ''
                        }`}
                      >
                        {uploadingSceneImage[scene.id] ? (
                          <span className="flex items-center justify-center gap-1">
                            <RefreshCw className="w-3 h-3 animate-spin" />
                            上传中...
                          </span>
                        ) : (
                          '上传图片'
                        )}
                      </label>
                    </div>
                  </div>
                  
                  {/* 信息 */}
                  <div className="flex-1 space-y-3">
                    <div className="flex items-center justify-between">
                      <h5 className="font-medium text-slate-700">分镜 {scene.sequence}</h5>
                      <div className="flex items-center gap-2">
                        <span className="text-xs px-2 py-1 bg-purple-100 text-purple-700 rounded">
                          时长: {scene.duration}s
                        </span>
                        {/* 排序按钮 */}
                        <div className="flex gap-1">
                          <button
                            onClick={() => handleMoveSceneUp(scene.id)}
                            disabled={scenes.findIndex(s => s.id === scene.id) === 0}
                            className="px-2 py-1 text-xs border border-slate-200 text-slate-600 rounded hover:bg-slate-50 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
                            title="上移"
                          >
                            <ChevronLeft className="w-3 h-3 rotate-90" />
                          </button>
                          <button
                            onClick={() => handleMoveSceneDown(scene.id)}
                            disabled={scenes.findIndex(s => s.id === scene.id) === scenes.length - 1}
                            className="px-2 py-1 text-xs border border-slate-200 text-slate-600 rounded hover:bg-slate-50 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
                            title="下移"
                          >
                            <ChevronLeft className="w-3 h-3 -rotate-90" />
                          </button>
                        </div>
                        <button
                          onClick={() => handleGenerateSceneImage(scene.id)}
                          disabled={isGeneratingSceneImage[scene.id]}
                          className="px-3 py-1 text-xs border border-purple-200 text-purple-600 rounded hover:bg-purple-50 disabled:opacity-50 transition-colors flex items-center gap-1"
                        >
                          {isGeneratingSceneImage[scene.id] ? (
                            <>
                              <RefreshCw className="w-3 h-3 animate-spin" />
                              生成中...
                            </>
                          ) : scene.generatedImage ? (
                            <>
                              <RefreshCw className="w-3 h-3" />
                              重新生成
                            </>
                          ) : (
                            <>
                              <Wand2 className="w-3 h-3" />
                              生成图片
                            </>
                          )}
                        </button>
                        <button
                          onClick={() => handleDeleteScene(scene.id)}
                          className="px-3 py-1 text-xs border border-red-200 text-red-600 rounded hover:bg-red-50 transition-colors flex items-center gap-1"
                          title="删除分镜"
                        >
                          <Trash2 className="w-3 h-3" />
                        </button>
                      </div>
                    </div>
                    
                    <div>
                      <label className="text-xs text-slate-500 font-medium">描述：</label>
                      <textarea
                        value={scene.description}
                        onChange={(e) => handleUpdateScene(scene.id, 'description', e.target.value)}
                        className="w-full mt-1 p-2 text-sm border border-slate-200 rounded focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                        rows={2}
                        placeholder="输入分镜描述..."
                      />
                    </div>
                    
                    <div>
                      <label className="text-xs text-slate-500 font-medium">提示词：</label>
                      <textarea
                        value={scene.prompt}
                        onChange={(e) => handleUpdateScene(scene.id, 'prompt', e.target.value)}
                        className="w-full mt-1 p-2 text-sm border border-slate-200 rounded focus:ring-2 focus:ring-purple-500 focus:border-transparent bg-slate-50"
                        rows={2}
                        placeholder="输入提示词..."
                      />
                    </div>
                    
                    {/* {scene.imagePrompt && (
                      <div>
                        <span className="text-xs text-slate-500 font-medium">图片提示词：</span>
                        <p className="text-sm text-slate-600 mt-1 bg-blue-50 p-2 rounded">{scene.imagePrompt}</p>
                      </div>
                    )}
                     */}
                    {scene.thoughtProcess && (
                      <details className="text-xs">
                        <summary className="cursor-pointer text-slate-500 hover:text-slate-700">
                          查看思考过程
                        </summary>
                        <p className="mt-2 text-slate-600 bg-gray-50 p-2 rounded whitespace-pre-wrap">
                          {scene.thoughtProcess}
                        </p>
                      </details>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );

  // 渲染步骤3：生成视频
  const renderStep3 = () => (
    <div className="space-y-6">
      {!generatedVideoUrl ? (
        <div className="text-center py-8">
          <div className="bg-purple-50 border border-purple-200 rounded-lg p-6 mb-6">
            <h4 className="font-medium text-purple-800 mb-2">准备生成视频</h4>
            <p className="text-sm text-purple-600">
              已生成 {scenes.filter(s => s.generatedImage).length} 个分镜图片
            </p>
            <p className="text-xs text-slate-500 mt-2">
              点击下方按钮开始合成最终视频
            </p>
          </div>

          <button
            onClick={handleComposeVideo}
            disabled={isComposingVideo}
            className="px-8 py-4 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 transition-colors flex items-center gap-2 mx-auto text-lg"
          >
            {isComposingVideo ? (
              <>
                <RefreshCw className="w-5 h-5 animate-spin" />
                视频生成中...
              </>
            ) : (
              <>
                <Video className="w-5 h-5" />
                生成视频
              </>
            )}
          </button>
        </div>
      ) : (
        <div className="text-center py-8">
          <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-6">
            <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-3">
              <Check className="w-6 h-6 text-green-600" />
            </div>
            <h4 className="font-medium text-green-800 mb-2">视频生成成功！</h4>
            <p className="text-sm text-green-600">
              {storyboardTitle}
            </p>
          </div>

          <div className="aspect-video bg-slate-900 rounded-lg overflow-hidden mb-6">
            <video
              src={generatedVideoUrl}
              controls
              className="w-full h-full"
            />
          </div>
        </div>
      )}
    </div>
  );

  // 渲染当前步骤内容
  const renderCurrentStep = () => {
    switch (currentStep) {
      case 1: return renderStep1();
      case 2: return renderStep2();
      case 3: return renderStep3();
      default: return null;
    }
  };

  // 渲染底部按钮
  const renderFooterButtons = () => {
    // 步骤3的特殊按钮逻辑
    if (currentStep === 3) {
      if (generatedVideoUrl) {
        // 视频已生成，显示上一步和确认按钮
        return (
          <div className="flex justify-between">
            <button
              onClick={() => setCurrentStep(prev => prev - 1)}
              className="px-6 py-2 border-2 border-[#e5e3db] rounded-xl text-[#2d2d2d] hover:bg-[#fffbe6] hover:border-[#2d2d2d] transition-all flex items-center gap-2 font-medium"
            >
              <ChevronLeft className="w-4 h-4" />
              上一步
            </button>
            <div className="flex gap-3">
              <button
                onClick={() => {
                  if (generatedVideoUrl) {
                    const link = document.createElement('a');
                    link.href = generatedVideoUrl;
                    link.download = `video_${Date.now()}.mp4`;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                  }
                }}
                className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors flex items-center gap-2"
              >
                <Download className="w-5 h-5" />
                下载视频
              </button>
              {/* 暂时屏蔽确认按钮 */}
              {/* <button
                onClick={handleConfirm}
                className="px-8 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors flex items-center gap-2"
              >
                <Check className="w-5 h-5" />
                确认并添加到画布
              </button> */}
            </div>
          </div>
        );
      }
      // 视频未生成，显示上一步按钮
      return (
        <div className="flex justify-start">
          <button
            onClick={() => setCurrentStep(prev => prev - 1)}
            className="px-6 py-2 border-2 border-[#e5e3db] rounded-xl text-[#2d2d2d] hover:bg-[#fffbe6] hover:border-[#2d2d2d] transition-all flex items-center gap-2 font-medium"
          >
            <ChevronLeft className="w-4 h-4" />
            上一步
          </button>
        </div>
      );
    }

    return (
      <div className="flex justify-between">
        <button
          onClick={() => setCurrentStep(prev => prev - 1)}
          disabled={currentStep === 1}
          className="px-6 py-2 border-2 border-[#e5e3db] rounded-xl text-[#2d2d2d] hover:bg-[#fffbe6] hover:border-[#2d2d2d] disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center gap-2 font-medium"
        >
          <ChevronLeft className="w-4 h-4" />
          上一步
        </button>

        {currentStep === 1 && (
          <button
            onClick={handleStep1Next}
            disabled={isGeneratingScript}
            className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center gap-2"
          >
            {isGeneratingScript ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                生成分镜中...
              </>
            ) : (
              <>
                下一步
                <ChevronRight className="w-4 h-4" />
              </>
            )}
          </button>
        )}

        {currentStep === 2 && (
          <button
            onClick={handleStep2Next}
            disabled={isGeneratingScript}
            className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 transition-colors flex items-center gap-2"
          >
            下一步
            <ChevronRight className="w-4 h-4" />
          </button>
        )}
      </div>
    );
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-4xl h-[740px] flex flex-col">
        {/* Header */}
        <div className="p-6 border-b-2 border-[#e5e3db] flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="bg-purple-600 p-2 rounded-lg text-white">
              <Video className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-lg text-slate-800">AI视频生成</h3>
              <p className="text-xs text-slate-500">{STEPS.find(s => s.id === currentStep)?.description}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Step Indicator */}
        <div className="px-6 pt-6">
          {renderStepIndicator()}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6" style={{ maxHeight: '480px' }}>
          {renderCurrentStep()}
          
          {error && (
            <div className="mt-4 p-3 bg-red-50 border border-red-200 text-red-600 text-sm rounded-lg flex items-center gap-2">
              <AlertCircle className="w-4 h-4" />
              {error}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-6 border-t-2 border-[#e5e3db]">
          {renderFooterButtons()}
        </div>
      </div>

      {/* 分镜图片放大预览 */}
      {previewImage && (
        <div
          className="fixed inset-0 z-[60] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4"
          onMouseDown={closePreviewImage}
          role="dialog"
          aria-modal="true"
        >
          <div className="relative" onMouseDown={(e) => e.stopPropagation()}>
            <button
              type="button"
              onClick={closePreviewImage}
              className="absolute -top-3 -right-3 bg-white/90 hover:bg-white text-slate-700 rounded-full p-2 shadow"
              aria-label="关闭预览"
            >
              <X className="w-5 h-5" />
            </button>
            <img
              src={previewImage.url}
              alt={previewImage.alt}
              className="max-h-[85vh] max-w-[90vw] object-contain rounded-lg shadow-2xl bg-black"
            />
          </div>
        </div>
      )}
    </div>
  );
};

export default VideoStoryboardModal;
