export const statusOptions = [
  { value: 'all', label: '全部状态' },
  { value: 'draft', label: '草稿' },
  { value: 'published', label: '已发布' },
];

export const demoCourses = [
  {
    id: 'unit-3-animals',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'draft',
    age: '7-9岁',
    grade: 'G3',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '星际救援冒险',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#ff705d',
    coverTone: 'coral',
    active: true,
  },
  {
    id: 'transportation',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'published',
    age: '7-9岁',
    grade: 'G3',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '星际救援冒险',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#4482e5',
    coverTone: 'blue',
  },
  {
    id: 'emotion-skills',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'draft',
    age: '7-9岁',
    grade: 'G2',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '音乐星球',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#9966d0',
    coverTone: 'purple',
  },
  {
    id: 'know-my-emotions',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'draft',
    age: '7-9岁',
    grade: 'K1',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '情绪魔法森林',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#509f69',
    coverTone: 'green',
  },
  {
    id: 'numbers-counting',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'draft',
    age: '7-9岁',
    grade: 'K2',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '数学探险岛',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#edb100',
    coverTone: 'gold',
  },
  {
    id: 'phonics-letter-a',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'draft',
    age: '7-9岁',
    grade: 'G1',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '字母魔法师',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#f4785e',
    coverTone: 'rose',
  },
  {
    id: 'shapes-space',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'published',
    age: '7-9岁',
    grade: 'K1',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '几何乐园',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#4482e5',
    coverTone: 'sky',
  },
  {
    id: 'friendly-communication',
    title: '神奇的动物世界',
    unit: '神奇的动物世界',
    status: 'draft',
    age: '7-9岁',
    grade: 'G4',
    duration: '40分钟',
    classSize: '9-15人',
    theme: '合作任务站',
    updatedAt: '2026/04/13 10:06:30',
    accent: '#509f69',
    coverTone: 'mint',
  },
];
