export const statusOptions = [
  { value: 'all', label: '全部状态' },
  { value: 'draft', label: '草稿' },
  { value: 'published', label: '已发布' },
];

export const demoCourses = [
  {
    id: 'unit-3-animals',
    title: 'Unit 3: Animals (神奇的动物)',
    unit: 'Unit 3: Animals',
    status: 'draft',
    age: '8-9岁',
    grade: 'G3',
    duration: '40分钟',
    theme: '星际救援冒险',
    updatedAt: '2026/3/11',
    accent: '#ff705d',
    coverTone: 'coral',
    active: true,
  },
  {
    id: 'transportation',
    title: 'Theme: Transportation (交通工具)',
    unit: 'Theme: Transportation',
    status: 'draft',
    age: '5-6岁',
    grade: 'K2',
    duration: '30分钟',
    theme: '星际救援冒险',
    updatedAt: '2026/3/11',
    accent: '#4482e5',
    coverTone: 'blue',
  },
  {
    id: 'emotion-skills',
    title: '情绪管理技巧',
    unit: 'Emotion & Wellbeing',
    status: 'published',
    age: '7-8岁',
    grade: 'G2',
    duration: '40分钟',
    theme: '音乐星球',
    updatedAt: '2026/3/11',
    accent: '#9966d0',
    coverTone: 'purple',
  },
  {
    id: 'know-my-emotions',
    title: '认识我的情绪',
    unit: 'Social-Emotional',
    status: 'draft',
    age: '3-4岁',
    grade: 'K1',
    duration: '30分钟',
    theme: '情绪魔法森林',
    updatedAt: '2026/4/1',
    accent: '#509f69',
    coverTone: 'green',
  },
  {
    id: 'numbers-counting',
    title: '数字认知：1-10',
    unit: 'Numbers & Counting',
    status: 'published',
    age: '5-6岁',
    grade: 'K2',
    duration: '35分钟',
    theme: '数学探险岛',
    updatedAt: '2026/3/28',
    accent: '#edb100',
    coverTone: 'gold',
  },
  {
    id: 'phonics-letter-a',
    title: 'Phonics: Letter A',
    unit: 'Phonics & Reading',
    status: 'draft',
    age: '7-8岁',
    grade: 'G1',
    duration: '45分钟',
    theme: '字母魔法师',
    updatedAt: '2026/4/2',
    accent: '#f4785e',
    coverTone: 'rose',
  },
  {
    id: 'shapes-space',
    title: '形状与空间',
    unit: 'Shapes & Space',
    status: 'published',
    age: '4-5岁',
    grade: 'K1',
    duration: '30分钟',
    theme: '几何乐园',
    updatedAt: '2026/4/7',
    accent: '#4482e5',
    coverTone: 'sky',
  },
  {
    id: 'friendly-communication',
    title: '友好沟通小课堂',
    unit: 'Communication',
    status: 'draft',
    age: '8-10岁',
    grade: 'G4',
    duration: '40分钟',
    theme: '合作任务站',
    updatedAt: '2026/4/10',
    accent: '#509f69',
    coverTone: 'mint',
  },
];
